<?php
/**
 * Shortlist demonstration — the design's fictional sample data, ported verbatim.
 * These are the DEFAULTS; the Home page's Shortlist tab (ACF Pro repeaters) overrides them.
 * ALL PROFILES ARE FICTIONAL. Stage index for exits_at: 2 Evaluate · 3 Interview · 4 Vet · 5 Decide · 0 finalist.
 */
defined( 'ABSPATH' ) || exit;

function hsg_shortlist_default_criteria(): array { return array( 'Multi-site operations', 'P&L responsibility', 'Leadership development', 'Process improvement', 'Cross-functional communication', 'Growth-stage experience' ); }

function hsg_shortlist_stages(): array { return apply_filters( 'hsg_shortlist_stages', array( array( 'key' => 'Understand', 'note' => 'Requirements agreed with the leadership team before a single candidate is contacted.', 'hot' => array( 0, 1, 2, 3, 4, 5 ) ), array( 'key' => 'Search', 'note' => 'Sourcing across HSG\'s network, referrals, and direct outreach.', 'hot' => array(  ) ), array( 'key' => 'Evaluate', 'note' => 'Scope and accountability measured against what the role actually requires.', 'hot' => array( 0, 1 ) ), array( 'key' => 'Interview', 'note' => 'Conversations that test how each person actually leads and communicates.', 'hot' => array( 2, 4 ) ), array( 'key' => 'Vet', 'note' => 'Private Vetting adds context that references alone rarely surface.', 'hot' => array( 3 ) ), array( 'key' => 'Decide', 'note' => 'Leadership, culture, working style, motivation, and long-term fit.', 'hot' => array( 5 ) ) ) ); }

function hsg_shortlist_default_candidates(): array {
	return array(
		array( 'role' => 'Director of Operations', 'years' => 14, 'industry' => 'Consumer Products', 'team' => '55', 'scope' => '$38M unit', 'c' => array( 0, 1, 2, 2, 1, 1 ), 'strength' => 'Process improvement', 'watch' => 'First potential VP role', 'exits_at' => 2, 'exit_reason' => 'No multi-site operations experience' ),
		array( 'role' => 'Plant General Manager', 'years' => 17, 'industry' => 'Manufacturing', 'team' => '120', 'scope' => '$65M facility', 'c' => array( 0, 2, 2, 2, 1, 1 ), 'strength' => 'Culture turnaround', 'watch' => 'Limited corporate-level exposure', 'exits_at' => 2, 'exit_reason' => 'Single-site scope only' ),
		array( 'role' => 'Operations Manager', 'years' => 11, 'industry' => 'Packaging', 'team' => '40', 'scope' => 'Department budget', 'c' => array( 0, 0, 1, 2, 1, 1 ), 'strength' => 'Scheduling discipline', 'watch' => 'No budget ownership', 'exits_at' => 2, 'exit_reason' => 'No P&L responsibility' ),
		array( 'role' => 'Director of Manufacturing', 'years' => 15, 'industry' => 'Automotive Supply', 'team' => '90', 'scope' => '$44M plant', 'c' => array( 0, 1, 1, 2, 1, 0 ), 'strength' => 'Lean deployment', 'watch' => 'Narrow commercial exposure', 'exits_at' => 2, 'exit_reason' => 'Single-site scope only' ),
		array( 'role' => 'Senior Operations Manager', 'years' => 12, 'industry' => 'Food & Beverage', 'team' => '65', 'scope' => 'Cost centre', 'c' => array( 0, 0, 1, 2, 2, 1 ), 'strength' => 'Throughput gains', 'watch' => 'Has not carried a P&L', 'exits_at' => 2, 'exit_reason' => 'No P&L responsibility' ),
		array( 'role' => 'Director of Continuous Improvement', 'years' => 16, 'industry' => 'Electronics', 'team' => '22', 'scope' => 'Programme budget', 'c' => array( 1, 0, 1, 2, 2, 1 ), 'strength' => 'Six Sigma programme design', 'watch' => 'Staff rather than line role', 'exits_at' => 2, 'exit_reason' => 'No P&L responsibility' ),
		array( 'role' => 'Plant Manager', 'years' => 19, 'industry' => 'Chemicals', 'team' => '140', 'scope' => '$58M site', 'c' => array( 0, 1, 2, 2, 1, 1 ), 'strength' => 'Safety record', 'watch' => 'Long tenure at one site', 'exits_at' => 2, 'exit_reason' => 'Single-site scope only' ),
		array( 'role' => 'Operations Director', 'years' => 13, 'industry' => 'Printing', 'team' => '48', 'scope' => '$21M unit', 'c' => array( 0, 1, 1, 1, 1, 1 ), 'strength' => 'Client delivery', 'watch' => 'Declining sector experience', 'exits_at' => 2, 'exit_reason' => 'Scope below the role requirement' ),
		array( 'role' => 'VP Manufacturing', 'years' => 22, 'industry' => 'Textiles', 'team' => '210', 'scope' => '$95M', 'c' => array( 1, 2, 2, 1, 1, 0 ), 'strength' => 'Capacity planning', 'watch' => 'Two sites, closely co-located', 'exits_at' => 2, 'exit_reason' => 'Multi-site exposure limited to two locations' ),
		array( 'role' => 'Director of Logistics', 'years' => 14, 'industry' => 'Distribution', 'team' => '70', 'scope' => 'Network budget', 'c' => array( 1, 0, 1, 2, 2, 1 ), 'strength' => 'Carrier negotiation', 'watch' => 'Functional rather than general management', 'exits_at' => 2, 'exit_reason' => 'No P&L responsibility' ),
		array( 'role' => 'General Manager', 'years' => 18, 'industry' => 'Building Products', 'team' => '85', 'scope' => '$40M branch', 'c' => array( 0, 2, 1, 1, 1, 1 ), 'strength' => 'Branch turnaround', 'watch' => 'Regional remit only', 'exits_at' => 2, 'exit_reason' => 'Single-site scope only' ),
		array( 'role' => 'Operations Lead', 'years' => 9, 'industry' => 'Contract Manufacturing', 'team' => '30', 'scope' => 'Cost centre', 'c' => array( 0, 0, 1, 2, 1, 2 ), 'strength' => 'Rapid ramp-up', 'watch' => 'Early in management career', 'exits_at' => 2, 'exit_reason' => 'No P&L responsibility' ),
		array( 'role' => 'Director of Operations', 'years' => 16, 'industry' => 'Medical Devices', 'team' => '58', 'scope' => '$33M', 'c' => array( 0, 1, 2, 2, 2, 1 ), 'strength' => 'Regulated environment delivery', 'watch' => 'Single facility throughout career', 'exits_at' => 2, 'exit_reason' => 'No multi-site operations experience' ),
		array( 'role' => 'Plant Director', 'years' => 20, 'industry' => 'Metal Fabrication', 'team' => '160', 'scope' => '$72M site', 'c' => array( 0, 2, 1, 2, 1, 0 ), 'strength' => 'Capital project delivery', 'watch' => 'Little exposure outside operations', 'exits_at' => 2, 'exit_reason' => 'Single-site scope only' ),
		array( 'role' => 'Manufacturing Manager', 'years' => 10, 'industry' => 'Plastics', 'team' => '35', 'scope' => 'Department', 'c' => array( 0, 0, 1, 2, 1, 1 ), 'strength' => 'Changeover reduction', 'watch' => 'No general management remit', 'exits_at' => 2, 'exit_reason' => 'No P&L responsibility' ),
		array( 'role' => 'Regional Manager', 'years' => 15, 'industry' => 'Industrial Services', 'team' => '60', 'scope' => '$26M region', 'c' => array( 1, 1, 1, 1, 2, 1 ), 'strength' => 'Customer retention', 'watch' => 'Service rather than production', 'exits_at' => 2, 'exit_reason' => 'Scope below the role requirement' ),
		array( 'role' => 'Director of Supply Chain', 'years' => 17, 'industry' => 'Apparel', 'team' => '42', 'scope' => 'Function budget', 'c' => array( 1, 0, 2, 2, 2, 1 ), 'strength' => 'Supplier development', 'watch' => 'Functional leadership only', 'exits_at' => 2, 'exit_reason' => 'No P&L responsibility' ),
		array( 'role' => 'Operations Director', 'years' => 12, 'industry' => 'E-commerce Fulfilment', 'team' => '110', 'scope' => '$29M', 'c' => array( 1, 1, 1, 2, 1, 2 ), 'strength' => 'Peak season scaling', 'watch' => 'Short tenure pattern', 'exits_at' => 2, 'exit_reason' => 'Scope below the role requirement' ),
		array( 'role' => 'Site Operations Manager', 'years' => 13, 'industry' => 'Aerospace Components', 'team' => '75', 'scope' => 'Cost centre', 'c' => array( 0, 0, 2, 2, 1, 1 ), 'strength' => 'Quality systems', 'watch' => 'No commercial accountability', 'exits_at' => 2, 'exit_reason' => 'No P&L responsibility' ),
		array( 'role' => 'Director of Production', 'years' => 18, 'industry' => 'Furniture', 'team' => '95', 'scope' => '$36M plant', 'c' => array( 0, 1, 1, 2, 1, 0 ), 'strength' => 'Labour relations', 'watch' => 'Mature, static business', 'exits_at' => 2, 'exit_reason' => 'Single-site scope only' ),
		array( 'role' => 'Operations Manager', 'years' => 8, 'industry' => 'Specialty Materials', 'team' => '24', 'scope' => 'Department', 'c' => array( 0, 0, 1, 1, 1, 2 ), 'strength' => 'Technical depth', 'watch' => 'Limited management span', 'exits_at' => 2, 'exit_reason' => 'No P&L responsibility' ),
		array( 'role' => 'Divisional Operations Manager', 'years' => 16, 'industry' => 'Pharma Services', 'team' => '68', 'scope' => '$31M', 'c' => array( 1, 1, 1, 2, 2, 1 ), 'strength' => 'Validation and compliance', 'watch' => 'Division smaller than target', 'exits_at' => 2, 'exit_reason' => 'Scope below the role requirement' ),
		array( 'role' => 'Plant General Manager', 'years' => 21, 'industry' => 'Industrial Manufacturing', 'team' => '175', 'scope' => '$88M site', 'c' => array( 0, 2, 2, 1, 1, 1 ), 'strength' => 'Union negotiation', 'watch' => 'One employer for 15 years', 'exits_at' => 2, 'exit_reason' => 'Single-site scope only' ),
		array( 'role' => 'Director of Fulfilment', 'years' => 12, 'industry' => 'Consumer Products', 'team' => '130', 'scope' => 'Network budget', 'c' => array( 1, 0, 1, 2, 1, 1 ), 'strength' => 'Automation rollout', 'watch' => 'Reports into supply chain, not GM', 'exits_at' => 2, 'exit_reason' => 'No P&L responsibility' ),
		array( 'role' => 'Operations Director', 'years' => 14, 'industry' => 'Third-Party Logistics', 'team' => '80', 'scope' => '$24M', 'c' => array( 1, 1, 1, 1, 2, 1 ), 'strength' => 'Client onboarding', 'watch' => 'Contract operations only', 'exits_at' => 2, 'exit_reason' => 'Scope below the role requirement' ),
		array( 'role' => 'VP Operations', 'years' => 19, 'industry' => 'Distribution', 'team' => '150', 'scope' => '$78M P&L', 'c' => array( 2, 2, 1, 2, 1, 1 ), 'strength' => 'Network optimisation', 'watch' => 'Runs lean on succession planning', 'exits_at' => 3, 'exit_reason' => 'Limited evidence of developing leaders beneath them' ),
		array( 'role' => 'SVP Operations', 'years' => 26, 'industry' => 'Logistics', 'team' => '450+', 'scope' => 'Multi-state P&L', 'c' => array( 2, 2, 1, 2, 0, 1 ), 'strength' => 'Complex operations', 'watch' => 'Industry transition required', 'exits_at' => 3, 'exit_reason' => 'Cross-functional working style raised concerns' ),
		array( 'role' => 'VP Operations', 'years' => 17, 'industry' => 'Packaging', 'team' => '165', 'scope' => '$70M P&L', 'c' => array( 2, 2, 0, 2, 2, 1 ), 'strength' => 'Cost discipline', 'watch' => 'High turnover in prior teams', 'exits_at' => 3, 'exit_reason' => 'No track record of leadership development' ),
		array( 'role' => 'COO', 'years' => 24, 'industry' => 'Distribution', 'team' => '300+', 'scope' => '$190M', 'c' => array( 2, 2, 1, 1, 1, 0 ), 'strength' => 'Scaling operations', 'watch' => 'Compensation may exceed range', 'exits_at' => 3, 'exit_reason' => 'Limited evidence of developing leaders beneath them' ),
		array( 'role' => 'VP Manufacturing', 'years' => 20, 'industry' => 'Chemicals', 'team' => '220', 'scope' => '$105M P&L', 'c' => array( 2, 2, 1, 2, 0, 1 ), 'strength' => 'Technical operations', 'watch' => 'Prefers to work through operations only', 'exits_at' => 3, 'exit_reason' => 'Cross-functional working style raised concerns' ),
		array( 'role' => 'VP Operations', 'years' => 18, 'industry' => 'Food & Beverage', 'team' => '190', 'scope' => '$82M P&L', 'c' => array( 2, 2, 0, 2, 1, 2 ), 'strength' => 'Rapid expansion delivery', 'watch' => 'Team built by hiring, not developing', 'exits_at' => 3, 'exit_reason' => 'No track record of leadership development' ),
		array( 'role' => 'VP Supply Chain & Operations', 'years' => 19, 'industry' => 'Medical Devices', 'team' => '95', 'scope' => '$80M division', 'c' => array( 2, 2, 1, 2, 1, 1 ), 'strength' => 'Cross-functional leadership', 'watch' => 'Less direct commercial exposure', 'exits_at' => 3, 'exit_reason' => 'Limited evidence of developing leaders beneath them' ),
		array( 'role' => 'Group Operations Director', 'years' => 22, 'industry' => 'Building Products', 'team' => '240', 'scope' => '$96M P&L', 'c' => array( 2, 2, 1, 1, 0, 1 ), 'strength' => 'Multi-site consolidation', 'watch' => 'Communication style described as directive', 'exits_at' => 3, 'exit_reason' => 'Cross-functional working style raised concerns' ),
		array( 'role' => 'VP Operations', 'years' => 16, 'industry' => 'Electronics', 'team' => '115', 'scope' => '$61M P&L', 'c' => array( 2, 2, 0, 2, 2, 2 ), 'strength' => 'New product introduction', 'watch' => 'First VP tenure still short', 'exits_at' => 3, 'exit_reason' => 'No track record of leadership development' ),
		array( 'role' => 'Divisional VP', 'years' => 23, 'industry' => 'Automotive Supply', 'team' => '260', 'scope' => '$130M P&L', 'c' => array( 2, 2, 1, 2, 0, 0 ), 'strength' => 'Programme management', 'watch' => 'Sector in structural decline', 'exits_at' => 3, 'exit_reason' => 'Cross-functional working style raised concerns' ),
		array( 'role' => 'VP Operations', 'years' => 21, 'industry' => 'Plastics', 'team' => '140', 'scope' => '$74M P&L', 'c' => array( 2, 2, 1, 1, 1, 1 ), 'strength' => 'Asset utilisation', 'watch' => 'Bench strength thin', 'exits_at' => 3, 'exit_reason' => 'Limited evidence of developing leaders beneath them' ),
		array( 'role' => 'Head of Operations', 'years' => 18, 'industry' => 'Pharma Services', 'team' => '125', 'scope' => '$67M P&L', 'c' => array( 2, 2, 1, 2, 0, 2 ), 'strength' => 'Regulated scale-up', 'watch' => 'Strained relationship with commercial team', 'exits_at' => 3, 'exit_reason' => 'Cross-functional working style raised concerns' ),
		array( 'role' => 'VP Operations', 'years' => 25, 'industry' => 'Metal Fabrication', 'team' => '205', 'scope' => '$112M P&L', 'c' => array( 2, 2, 0, 2, 1, 0 ), 'strength' => 'Operational recovery', 'watch' => 'Mature business throughout', 'exits_at' => 3, 'exit_reason' => 'No track record of leadership development' ),
		array( 'role' => 'VP Operations', 'years' => 20, 'industry' => 'Industrial Manufacturing', 'team' => '180+', 'scope' => '$120M P&L', 'c' => array( 2, 2, 2, 1, 2, 1 ), 'strength' => 'Multi-site leadership', 'watch' => 'Limited recent transformation work', 'exits_at' => 4, 'exit_reason' => 'Process improvement depth did not hold up under vetting' ),
		array( 'role' => 'COO', 'years' => 23, 'industry' => 'Consumer Products', 'team' => '280', 'scope' => '$155M', 'c' => array( 2, 2, 2, 1, 2, 2 ), 'strength' => 'Commercial partnership', 'watch' => 'Improvement results largely inherited', 'exits_at' => 4, 'exit_reason' => 'Improvement record thinner than presented' ),
		array( 'role' => 'VP Global Operations', 'years' => 27, 'industry' => 'Aerospace Components', 'team' => '310', 'scope' => '$168M P&L', 'c' => array( 2, 2, 2, 0, 2, 1 ), 'strength' => 'International footprint', 'watch' => 'Delegated all improvement work', 'exits_at' => 4, 'exit_reason' => 'No sustained ownership of process improvement' ),
		array( 'role' => 'SVP Operations', 'years' => 24, 'industry' => 'Third-Party Logistics', 'team' => '390', 'scope' => '$140M P&L', 'c' => array( 2, 2, 2, 1, 2, 0 ), 'strength' => 'Client scale delivery', 'watch' => 'Growth came through acquisition only', 'exits_at' => 4, 'exit_reason' => 'Process improvement depth did not hold up under vetting' ),
		array( 'role' => 'VP Operations', 'years' => 19, 'industry' => 'Furniture', 'team' => '160', 'scope' => '$76M P&L', 'c' => array( 2, 2, 2, 1, 1, 2 ), 'strength' => 'Demand volatility management', 'watch' => 'Results difficult to corroborate', 'exits_at' => 4, 'exit_reason' => 'Improvement record thinner than presented' ),
		array( 'role' => 'Group COO', 'years' => 26, 'industry' => 'Specialty Materials', 'team' => '340', 'scope' => '$175M', 'c' => array( 2, 2, 2, 0, 2, 1 ), 'strength' => 'Portfolio oversight', 'watch' => 'Distant from operating detail', 'exits_at' => 4, 'exit_reason' => 'No sustained ownership of process improvement' ),
		array( 'role' => 'VP Operations', 'years' => 21, 'industry' => 'Industrial Manufacturing', 'team' => '180+', 'scope' => '$120M P&L', 'c' => array( 2, 2, 2, 2, 2, 1 ), 'strength' => 'Multi-site leadership at scale', 'watch' => 'Career built in mature, stable businesses', 'exits_at' => 5, 'exit_reason' => 'Growth-stage experience below the requirement' ),
		array( 'role' => 'COO', 'years' => 22, 'industry' => 'Distribution', 'team' => '265', 'scope' => '$148M', 'c' => array( 2, 2, 2, 2, 2, 0 ), 'strength' => 'Running a large, steady operation', 'watch' => 'No expansion-phase exposure', 'exits_at' => 5, 'exit_reason' => 'No growth-stage experience' ),
		array( 'role' => 'VP Operations', 'years' => 24, 'industry' => 'Packaging', 'team' => '215', 'scope' => '$118M P&L', 'c' => array( 2, 2, 2, 2, 2, 1 ), 'strength' => 'Complex multi-site delivery', 'watch' => 'Growth limited to acquisition integration', 'exits_at' => 5, 'exit_reason' => 'Growth-stage experience below the requirement' ),
		array( 'role' => 'VP Operations', 'years' => 18, 'industry' => 'Industrial Manufacturing', 'team' => '165', 'scope' => '$92M P&L', 'c' => array( 2, 2, 2, 2, 2, 2 ), 'strength' => 'Opened two greenfield sites while running the core business', 'watch' => 'Would relocate; timing tied to a Q3 milestone', 'exits_at' => 0, 'exit_reason' => '' ),
		array( 'role' => 'COO', 'years' => 20, 'industry' => 'Consumer Products', 'team' => '240', 'scope' => '$134M', 'c' => array( 2, 2, 2, 2, 2, 2 ), 'strength' => 'Took the business from $60M to $134M in six years', 'watch' => 'Compensation sits at the top of the range', 'exits_at' => 0, 'exit_reason' => '' ),
		array( 'role' => 'VP Operations', 'years' => 16, 'industry' => 'Medical Devices', 'team' => '140', 'scope' => '$88M P&L', 'c' => array( 2, 2, 2, 2, 2, 2 ), 'strength' => 'Developed four direct reports into general management roles', 'watch' => 'Least tenured of the three finalists', 'exits_at' => 0, 'exit_reason' => '' ),
	);
}
